export const presetSelectCopy = {
  eyebrow: 'Booth',
  title: '원하는 룩을 골라 주세요',
  description: '대표 이미지를 보고 마음에 드는 하나를 고르면 다음 촬영부터 바로 적용돼요.',
  sessionLabel: '지금 세션',
  sessionDescription: '이 세션에 적용할 프리셋을 하나만 고를 수 있어요.',
  loadingTitle: '프리셋을 준비하고 있어요',
  loadingDescription: '화면에 보여 줄 옵션을 확인하고 있어요.',
  errorTitle: '프리셋을 다시 확인할게요',
  emptyTitle: '지금은 고를 수 있는 룩을 준비 중이에요',
  emptyDescription: '잠시 후 다시 확인해 주세요.',
  guidanceTitle: '다음 단계',
  guidanceDescription: '대표 이미지를 보고 원하는 분위기를 골라 주세요.',
  selectedDescription: '선택한 룩이 다음 촬영부터 적용돼요.',
  saveLabel: '이 룩으로 진행할게요',
  savingLabel: '선택을 저장하고 있어요...',
  selectedLabel: '선택됨',
  retryLabel: '다시 불러올게요',
  loadErrorDescription: '지금은 프리셋을 불러올 수 없어요. 잠시 후 다시 시도해 주세요.',
  saveErrorDescription: '선택을 저장하지 못했어요. 다시 한 번 눌러 주세요.',
} as const
