$ErrorActionPreference = 'Stop'
$env:BOOTHY_APPROVED_CUSTOMER_MONITOR = '\\.\DISPLAY1'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = '--remote-debugging-port=9224'
$env:RUST_LOG = 'info'
Set-Location -LiteralPath 'C:\Code\Boothy'
& pnpm.cmd tauri dev --no-watch *> 'C:\Code\Boothy\tests\hardware\viewer-present\run-20260811-135652\logs\unapproved-display1.log'
